### ISSUE TITLE
TypeError: 'spacy.tokens.token.Token' object is not iterable

### ISSUE THREAD

**Issue by GhibliField** [cedias/Hierarchical-Sentiment#3]
How can I get rid of this? plz help 

--------------------------------
Hierarchical Attention Network:
--------------------------------
Building train/test of split #0: 100%|█| 37126/37126 [00:00<00:00, 3205519.58it/s]
Tuples rows are the following:
{'user_id': 0, 'item_id': 1, 'review': 2, 'rating': 3}
Traceback (most recent call last):
  File "han.py", line 224, in <module>
    main(args)
  File "han.py", line 160, in main
    data_tl, (train_set, val_set, test_set), net, wdict = load(args)
  File "han.py", line 123, in load
    wdict = data_tl.get_field_dict("review",key_iter=trainit,offset=2, max_count=args.max_feat, iter_func=(lambda x: (w for s in x for w in s )))
  File "/home/d0main/wyshen/Hierarchical-Sentiment/fmtl.py", line 160, in get_field_dict
    d =  Counter(field_gen)
  File "/home/d0main/anaconda3/lib/python3.6/collections/__init__.py", line 535, in __init__
    self.update(*args, **kwds)
  File "/home/d0main/anaconda3/lib/python3.6/collections/__init__.py", line 622, in update
    _count_elements(self, iterable)
TypeError: 'spacy.tokens.token.Token' object is not iterable

My environment:
- pytorch  0.4.0
- python3.6 (anaconda)
- ubuntu16.04

**Comment by larry0123du** [comment]
@GhibliField How did you solve this? Thanks!

**Comment by brandenchan** [comment]
@larry0123du I solved this by installing Spacy==1.9 (I was using Spacy==2.0 before)

**Comment by SunYanCN** [comment]
if word is "spacy.tokens.token.Token",you can chage it to "word.text" in Spacy==2.018
